export const orders = [
  {
    orderId: crypto.randomUUID(),
    orderNumber: "#3210",
    customer: "Olivia Martin",
    channel: "Online Store",
    date: "February 20, 2022",
    total: "$42.25",
    status: "Shipped",
  },
  {
    orderId: crypto.randomUUID(),
    orderNumber: "#3209",
    customer: "Ava Johnson",
    channel: "Shop",
    date: "January 5, 2022",
    total: "$74.99",
    status: "Paid",
  },
  {
    orderId: crypto.randomUUID(),
    orderNumber: "#3204",
    customer: "Michael Johnson",
    channel: "Shop",
    date: "August 3, 2021",
    total: "$64.75",
    status: "Unfulfilled",
  },
  {
    orderId: crypto.randomUUID(),
    orderNumber: "#3203",
    customer: "Lisa Anderson",
    channel: "Online Store",
    date: "July 15, 2021",
    total: "$34.50",
    status: "Shipped",
  },
  {
    orderId: crypto.randomUUID(),
    orderNumber: "#3202",
    customer: "Samantha Green",
    channel: "Shop",
    date: "June 5, 2021",
    total: "$89.99",
    status: "Paid",
  },
  {
    orderId: crypto.randomUUID(),
    orderNumber: "#3201",
    customer: "Adam Barlow",
    channel: "Online Store",
    date: "May 20, 2021",
    total: "$24.99",
    status: "Unfulfilled",
  },
  {
    orderId: crypto.randomUUID(),
    orderNumber: "#3207",
    customer: "Sophia Anderson",
    channel: "Shop",
    date: "November 2, 2021",
    total: "$99.99",
    status: "Paid",
  },
  {
    orderId: crypto.randomUUID(),
    orderNumber: "#3206",
    customer: "Daniel Smith",
    channel: "Online Store",
    date: "October 7, 2021",
    total: "$67.50",
    status: "Shipped",
  },
];
